### ISSUE TITLE
I changed currency to USD and Invoice and Part pay disappeared in checkout, but with EUR all are active.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#11]

**Comment by Boxedsolutions** [comment]
Should be fixed now

**Comment by joakim-combain** [comment]
Now that I choose USD it gives me none of the billmate methods. It should give Card if I'm not mistaking? @andyjohansson

**Comment by andyjohansson** [comment]
Talked to @Boxedsolutions about it and he will implement it according to specification which has been updated.

**Comment by Boxedsolutions** [comment]
I have added all currencies according to the specification

**Comment by joakim-combain** [comment]
This is fixed. Closing it.
