### ISSUE TITLE
There seems to be issues with invoice fee, seems like you are not rounding the values or something.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#13]
I get this error message when trying to check out.

Billmate Error Code:9107. Total Payment with Tax is not equal to Total Payment Excluding Tax Total Tax Rounding.Calculated total: 32981 Provided total:32980.6

apilogsid: 14831

**Comment by Boxedsolutions** [comment]
Should be fixed now.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
