### ISSUE TITLE
Pclasses in checkout have same amount in 12 and 6 months, is this correct?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#16]
![oscommerce pclasses checkout](https://cloud.githubusercontent.com/assets/10434920/6936805/2b745f78-d856-11e4-8b79-dcd2548e8362.png)

Both 6 and 12 have 321,00kr, is this correct?

**Comment by joakim-combain** [comment]
Also, I just put an order and monthly cost according to the order in BO is 130, but that's not what it says in checkout.

Invoice number: 7377

**Comment by Boxedsolutions** [comment]
It should not be visible if not norway according to code. But I have updated the algo

**Comment by joakim-combain** [comment]
What do you mean "It should not be visible if not norway according to code."?

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-04-02 09 39 27](https://cloud.githubusercontent.com/assets/8977650/6959741/40c9a178-d91c-11e4-91a2-cb4f33c8ed89.png)
The code prevents it from show up. It was the total purchase cost, which we dont show in our other modules.

**Comment by andyjohansson** [comment]
So is this resolved? :+1:

**Comment by Boxedsolutions** [comment]
It calculates correct. Should be ready I think.
