### ISSUE TITLE
There is an issue with pclasses. I have a product costing 100 but I get all options.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#17]
Only 3 months should be visible for this case.

There seems to be several other issues with pclasses aswell, referred in #16.

**Comment by Boxedsolutions** [comment]
This is implemented now.

**Comment by joakim-combain** [comment]
I noticed an issue where if you use discount code, test123, the values are not recalculated. However, I'm not sure if we can actually update this value in OSC since discount codes are added in the last page.

I'm mostly wondering, is it possible to fix this? The problem is that we show a different value in store than what is used in billmate online.

**Comment by Boxedsolutions** [comment]
That is the problem, It is calculated on the last page. 
The next problem that may occur is that the customer use another coupon module, so I must think how to do if it possible to solve it.

**Comment by Boxedsolutions** [comment]
That is the problem, It is calculated on the last page. 
The next problem that may occur is that the customer use another coupon module, so I must think how to do if it possible to solve it.

**Comment by joakim-combain** [comment]
Everything is working otherwise so to me it's not a big deal but it would be good to look in to it and see if we can solve it in a good way.

**Comment by andyjohansson** [comment]
We leave it like this.
