### ISSUE TITLE
Change verify adress view to be same as Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/oscommerce#32]
Change this:
![skarmavbild 2015-06-10 kl 14 31 46](https://cloud.githubusercontent.com/assets/4968755/8082422/856e8c0c-0f7d-11e5-858e-23124a6f0d89.png)

To this:
![skarmavbild 2015-06-10 kl 14 32 09](https://cloud.githubusercontent.com/assets/4968755/8082423/89582c4c-0f7d-11e5-97d9-39780ea79c62.png)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Encoding issues.
![skarmavbild 2015-06-10 kl 20 06 18](https://cloud.githubusercontent.com/assets/4968755/8090097/3118ebbe-0fac-11e5-8d08-700bfb13dbe7.png)
