### ISSUE TITLE
Testmode should be displayed the same, always

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/oscommerce#33]
![skarmavbild 2015-06-10 kl 14 57 18](https://cloud.githubusercontent.com/assets/4968755/8082893/0d810e1e-0f81-11e5-94cd-0e7a43e174b8.png)

Should be (Testmode enabled)

**Comment by Boxedsolutions** [comment]
Should be fixed in c12e8ec..d728b9c

**Comment by andyjohansson** [comment]
Still issues?

![skarmavbild 2015-06-10 kl 19 52 46](https://cloud.githubusercontent.com/assets/4968755/8089779/51cea92c-0faa-11e5-89b1-29769130ed14.png)
