### ISSUE TITLE
Reverse the order of the part payment options

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/oscommerce#37]
The minimum duration needs to be first and selected by default, like on other modules.
![skarmavbild 2015-06-10 kl 20 09 24](https://cloud.githubusercontent.com/assets/4968755/8090163/a480f556-0fac-11e5-8ed6-fde3ebc93d56.png)
![skarmavbild 2015-06-10 kl 20 09 35](https://cloud.githubusercontent.com/assets/4968755/8090162/a47f1722-0fac-11e5-841e-4caa95d5193e.png)

**Comment by Boxedsolutions** [comment]
Should be implemented
