### ISSUE TITLE
In handladigitalt, if I put in 550505055 I get a weird error message. It should be the error message for ssn is too short.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#40]
![hd too short ssn message](https://cloud.githubusercontent.com/assets/10434920/8279566/efde48be-18d5-11e5-826c-ba7c0443a587.png)

**Comment by Boxedsolutions** [comment]
I did get a popup when the ssn is to short. 

I think you have to add products from the categories. The products on the startpage points to the real site. Verify your url.
