### ISSUE TITLE
In handladigitalt, if I put 5505050558 I get error message 1001 when I should get error message 2207

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#41]
![hd wrong error message](https://cloud.githubusercontent.com/assets/10434920/8279671/cddfe8ca-18d6-11e5-95e6-974fcb27b93c.png)

**Comment by Boxedsolutions** [comment]
![skarmklipp 2015-06-22 12 15 23](https://cloud.githubusercontent.com/assets/8977650/8279886/66a2eaf2-18d8-11e5-8214-b70a548a2494.png)

This is what I got for both Partpayment and Invoice

**Comment by joakim-combain** [comment]
Turns out I was testing on the real store. Some links on the front end leads there. I pressed "kikarsikte" for example. It sent me to the real store.
