### ISSUE TITLE
Is it ment to look like this? Shouldn't the logo appear when you select the payment method?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#42]
![hd checkout](https://cloud.githubusercontent.com/assets/10434920/8280250/cd566a28-18db-11e5-8bf8-9ea12fb44229.png)

**Comment by Boxedsolutions** [comment]
Its not implemented that way. I dont want to have a lot of javascript in OsCommerce as it is some issues some times, in different installations.

**Comment by joakim-combain** [comment]
Ok. Closing this issue.
