### ISSUE TITLE
Sort order is not working in handladigitalt.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#44]

**Comment by Boxedsolutions** [comment]
I am not sure how we should solve this as it is the standard we use.

**Comment by andyjohansson** [comment]
Could be a bug in OsCommerce.

**Comment by Boxedsolutions** [comment]
Its possible, but it work in a standard installation, it could be some thirdparty module that makes this.

**Comment by andyjohansson** [comment]
Ok, then we close it.
