### ISSUE TITLE
Country restrictions does not work for Bank. I could not disable for sweden. Either remove this option or make it possible to disable sweden.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#45]

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Implemented the same way as other modules?

**Comment by Boxedsolutions** [comment]
Yes it is now, its a 2 step check first check if it is a valid country and then check if the country is disabled. 
I think it will be more future safe that way.

**Comment by andyjohansson** [comment]
Ok, great. Then please verify @joakim-combain.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
