### ISSUE TITLE
Check so that you can check out correctly with another currency than SEK

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/oscommerce#7]
Invoice:
Test to checkout with other currency than SEK. Should be that currency in all declarations of the order.
Card:
Test to checkout with other currency than SEK. Should be that currency in all declarations of the order.

Also check so that the Invoice fee is displayed and handled correctly. It should be converted to the currency used in the checkout process.

**Comment by joakim-combain** [comment]
As of right now it works to check out with SEK and EUR. USD doesn't work. @andyjohansson  is this ok?

**Comment by Boxedsolutions** [comment]
I havent USD activated only. Only that.

**Comment by joakim-combain** [comment]
What do you mean activated? Is there an setting for plugin for this or?

**Comment by Boxedsolutions** [comment]
Its hardcoded. So I just have to Add this.

**Comment by joakim-combain** [comment]
Aha, ok, then I understand. But card should have all currencies shouldn't it? Just thinking if you should allow all currencies right now for card?

**Comment by Boxedsolutions** [comment]
I added USD for Card now it should just be to test it.

**Comment by Boxedsolutions** [comment]
I will add all active currencies for the methods that should have them.

**Comment by joakim-combain** [comment]
Ok, it works. Closing this issue.
