### ISSUE TITLE
Terms for part pay needs to be moved down one row, right now it's outside the dropdown function, unlike invoice.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/oscommerce#9]
![oscommerce terms](https://cloud.githubusercontent.com/assets/10434920/6918529/b9d0e1b2-d7af-11e4-9745-3fdfb7227849.png)

**Comment by Boxedsolutions** [comment]
Should be solved

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
